# Generated by Django 2.2.6 on 2019-10-19 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date1', models.DateField()),
                ('place', models.CharField(max_length=100)),
                ('worker', models.CharField(max_length=100)),
                ('thing', models.CharField(max_length=100)),
            ],
        ),
    ]
